=== moep/formattools/POITagMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.mapsforge.org/POITagMapping"
	xmlns:tns="http://www.mapsforge.org/POITagMapping" elementFormDefault="qualified">

	<element name="TagMappings">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<element name="Mapping">
					<complexType>
						<attribute name="tag" type="string"></attribute>
						<attribute name="categoryName" type="string"></attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

</schema>

=== moep/formattools/POIDefaultMappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:TagMappings xmlns:tns="http://www.mapsforge.org/POITagMapping"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mapsforge.org/POITagMapping POITagMapping.xsd ">
	<tns:Mapping categoryName="School grounds" tag="amenity=school" />
	<tns:Mapping categoryName="Hunting stands" tag="amenity=hunting_stand" />
	<tns:Mapping categoryName="Cafes" tag="amenity=cafe" />
	<tns:Mapping categoryName="A single parking space" tag="amenity=parking_space" />
	<tns:Mapping categoryName="Recycling facilities" tag="amenity=recycling" />
	<tns:Mapping categoryName="Fast food restaurants" tag="amenity=fast_food" />
	<tns:Mapping categoryName="Restaurants" tag="amenity=restaurant" />
	<tns:Mapping categoryName="Post boxes" tag="amenity=post_box" />
	<tns:Mapping categoryName="TV, radio or recording studios"
		tag="amenity=studio" />
	<tns:Mapping categoryName="Currency exchange places" tag="amenity=bureau_de_change" />
	<tns:Mapping categoryName="Garbage cans" tag="amenity=waste_basket" />
	<tns:Mapping categoryName="Theatres and operas" tag="amenity=theatre" />
	<tns:Mapping categoryName="Car rental stations" tag="amenity=car_rental" />
	<tns:Mapping categoryName="Food amenities" tag="amenity=[sustenance]" />
	<tns:Mapping categoryName="Entrances / Exits to underground parking facilities"
		tag="amenity=parking_entrance" />
	<tns:Mapping categoryName="Garbage containers" tag="amenity=waste_disposal" />
	<tns:Mapping categoryName="Dentists" tag="amenity=dentist" />
	<tns:Mapping categoryName="Public buildings" tag="amenity=public_building" />
	<tns:Mapping categoryName="Cinemas" tag="amenity=cinema" />
	<tns:Mapping categoryName="Crematoriums" tag="amenity=crematorium" />
	<tns:Mapping categoryName="Nightclubs (Dancing)" tag="amenity=nightclub" />
	<tns:Mapping categoryName="Beer gardens" tag="amenity=biergarten" />
	<tns:Mapping categoryName="Hospitals" tag="amenity=hospital" />
	<tns:Mapping categoryName="Community centers" tag="amenity=community_centre" />
	<tns:Mapping categoryName="All categories" tag="*" />
	<tns:Mapping categoryName="Food amenities" tag="amenity=[food]" />
	<tns:Mapping categoryName="Fuel stations" tag="amenity=fuel" />
	<tns:Mapping categoryName="Public visible clocks" tag="amenity=clock" />
	<tns:Mapping categoryName="Healthcare" tag="amenity=[healthcare]" />
	<tns:Mapping categoryName="Social Facilities" tag="amenity=social_facility" />
	<tns:Mapping categoryName="Town hall buildings" tag="amenity=townhall" />
	<tns:Mapping categoryName="Churches, mosques, temples" tag="amenity=place_of_worship" />
	<tns:Mapping categoryName="Containers holding a mixture of salt and grit"
		tag="amenity=grit_bin" />
	<tns:Mapping categoryName="Court houses" tag="amenity=courthouse" />
	<tns:Mapping categoryName="Vending machines" tag="amenity=vending_machine" />
	<tns:Mapping categoryName="Public libraries" tag="amenity=library" />
	<tns:Mapping categoryName="Entertainment, arts and culture"
		tag="amenity=[entertainment]" />
	<tns:Mapping categoryName="Entertainment, arts and culture"
		tag="amenity=[culture]" />
	<tns:Mapping categoryName="Amenity root category" tag="amenity=" />
	<tns:Mapping categoryName="College campus or buildings"
		tag="amenity=college" />
	<tns:Mapping categoryName="Public grills" tag="amenity=bbq" />
	<tns:Mapping categoryName="Car washing stations" tag="amenity=car_wash" />
	<tns:Mapping categoryName="Bars" tag="amenity=bar" />
	<tns:Mapping categoryName="Public benches" tag="amenity=bench" />
	<tns:Mapping categoryName="Water places for animals" tag="amenity=watering_place" />
	<tns:Mapping categoryName="Saunas" tag="amenity=sauna" />
	<tns:Mapping categoryName="Post offices" tag="amenity=post_office" />
	<tns:Mapping categoryName="Bad weather shelters" tag="amenity=shelter" />
	<tns:Mapping categoryName="Kindergartens" tag="amenity=kindergarten" />
	<tns:Mapping categoryName="Bicycle rental stations" tag="amenity=bicycle_rental" />
	<tns:Mapping categoryName="Education institutes" tag="amenity=[education]" />
	<tns:Mapping categoryName="Places to drop babies for remorse"
		tag="amenity=baby_hatch" />
	<tns:Mapping categoryName="Other amenities" tag="amenity=[others]" />
	<tns:Mapping categoryName="Embassies" tag="amenity=embassy" />
	<tns:Mapping categoryName="Public toilets" tag="amenity=toilets" />
	<tns:Mapping categoryName="Other amenities" tag="amenity=[other]" />
	<tns:Mapping categoryName="Amenity root category" tag="amenity=*" />
	<tns:Mapping categoryName="Electric vehicle charging facilities"
		tag="amenity=ev_charging" />
	<tns:Mapping categoryName="Brothels" tag="amenity=brothel" />
	<tns:Mapping categoryName="Social centers" tag="amenity=social_centre" />
	<tns:Mapping categoryName="ATMs and cash points" tag="amenity=atm" />
	<tns:Mapping categoryName="Fire stations" tag="amenity=fire_station" />
	<tns:Mapping categoryName="Entertainment, arts and culture"
		tag="amenity=[arts]" />
	<tns:Mapping categoryName="Nursing homes" tag="amenity=nursing_home" />
	<tns:Mapping categoryName="Police stations" tag="amenity=police" />
	<tns:Mapping categoryName="Fountains" tag="amenity=fountain" />
	<tns:Mapping categoryName="Ice cream shops" tag="amenity=ice_cream" />
	<tns:Mapping categoryName="Arts centers" tag="amenity=arts_centre" />
	<tns:Mapping categoryName="Transportation" tag="amenity=[transportation]" />
	<tns:Mapping categoryName="Pharmacies" tag="amenity=pharmacy" />
	<tns:Mapping categoryName="Financial institutes" tag="amenity=[financial]" />
	<tns:Mapping categoryName="Area with several different food counters"
		tag="amenity=food_court" />
	<tns:Mapping categoryName="Pubs" tag="amenity=pub" />
	<tns:Mapping categoryName="Drinking water sources" tag="amenity=drinking_water" />
	<tns:Mapping categoryName="Grave yards" tag="amenity=grave_yard" />
	<tns:Mapping categoryName="Marketplaces" tag="amenity=market_place" />
	<tns:Mapping categoryName="Veterinary clinics" tag="amenity=veterinary" />
	<tns:Mapping categoryName="Car sharing stations" tag="amenity=car_sharing" />
	<tns:Mapping categoryName="Car parks" tag="amenity=parking" />
	<tns:Mapping categoryName="Prisons (no schools)" tag="amenity=prison" />
	<tns:Mapping categoryName="Bus stations" tag="amenity=bus_station" />
	<tns:Mapping categoryName="Places where taxis wait for passengers"
		tag="amenity=taxi" />
	<tns:Mapping categoryName="Ice cream shops" tag="shop=ice_cream" />
	<tns:Mapping categoryName="Banks" tag="amenity=bank" />
	<tns:Mapping categoryName="Doctors's practises" tag="amenity=doctors" />
	<tns:Mapping categoryName="Places where you can enter leave a ferry"
		tag="amenity=ferry_terminal" />
	<tns:Mapping categoryName="Strip clubs" tag="amenity=stripclub" />
	<tns:Mapping categoryName="University campus or buildings"
		tag="amenity=university" />
	<tns:Mapping categoryName="Public telephones" tag="amenity=telephone" />
	<tns:Mapping categoryName="Places to park bicycles on" tag="amenity=bicycle_parking" />

</tns:TagMappings>
